web:
    build: ./web
    ports:
      - "8888:8888"
    links:
      - db
      - elasticsearch
    hostname: stockserver

db:
    hostname: stockserver
    build: ./mysql
    ports:
      - "3306:3306"

elasticsearch:
    hostname: stockserver
    build: ./elasticsearch
    ports:
     - "9200:9200"
     - "9300:9300"
